# Site settings
title: "IFML Prospectives on Generative AI - 2023"
email: jwhorley@utexas.edu
url:  "https://ifml-ut.github.io/GenAI-workshop23/"
description: "A workshop on generatative artificial intelligence at the University of Texas, Austin"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#444444'
  links: '#e8e3d3'

# Footer settings
footer: # Institute for Foundations of Machine Learning | ifml@austin.utexas.edu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: https://twitter.com/neurohackademy
  #- title: Github
  #  url: https://github.com/IFML-UT

# Build settings
markdown: kramdown
permalink: pretty

# Google Analytics
google_analytics: UA-XXXXXXXX-X
